### ISSUE TITLE
Patch 2.1.1

### ISSUE THREAD

**Issue by DrLarck** [DrLarck/dragonbotz#58]
**PATCH v2.1.1**

**__TO FIX__** : 

- [x] #56 : Somehow people have negative DS amount
- [x] #59 : The box doesn't display the correct amount of units
- [x] #60 : Recycled character in the player's team bug
- [x] When buying a character from the `shop character` the message "Can't retrieve the seller's data" is displayed
- [x] Fix the embed footer date

**__IMPROVEMENTS__**

- [x] Add lock/unlock by rarity
- [x] Display an error message when the game is rebooting
- [x] Add mod commands
- [x] Add vote command
- [x] Add invite command
- [x] Add premium/donate command
- [x] Increase LR rate from 0.01 % to 0.07 %
- [x] Some characters can't be traded (such as 299)
- [x] 10k compensation
- [x] Train doesn't make char level up ?
